In [1]:
import gym
from gym import logger as gymlogger
gymlogger.set_level(40) # error only
import pybulletgym  # register PyBullet enviroments with open ai gym
import numpy as np
from gym import wrappers

In [2]:
import torch
import torch.nn as nn
import torch.autograd as autograd

In [3]:
#define the simulated environment we are going to use
env = gym.make("InvertedPendulumMuJoCoEnv-v0")
#check out the pacman action space!
print(env.action_space)

# should return a state vector if everything worked (value doesn't matter)
env.reset()

Box(-1.0, 1.0, (1,), float32)


array([ 0.        , -0.02228618,  0.        ,  0.        ], dtype=float32)

In [13]:
env = gym.make("Walker2DMuJoCoEnv-v0")
print(env.action_space)

env.reset()

WalkerBase::__init__
Box(-1.0, 1.0, (6,), float32)


array([ 0.08488122,  0.05886491, -0.03090377, -0.01528817,  0.00391449,
       -0.00408916,  0.017515  , -0.05307111,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)

In [5]:
env = gym.make("HalfCheetahMuJoCoEnv-v0")
print(env.action_space)

env.reset()

WalkerBase::__init__
Box(-1.0, 1.0, (6,), float32)


array([-0.03515276, -0.03119576, -0.04723642,  0.03976043,  0.00682331,
        0.02454042, -0.07866516,  0.09989522,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)

In [10]:
env = gym.make("HalfCheetahMuJoCoEnv-v0")
env = wrappers.Monitor(env, './HalfCheetahVideo/')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

WalkerBase::__init__
